### ISSUE TITLE
8.3 Comenzamos Con Excepciones -> Parte 1, 2 , 3 y 4

### ISSUE THREAD

**Issue by MauryCerda** [CodeSystem2022/HE-MAN-TercerSemestre-2023#127]

**Comment by FernandoCala** [comment]
Subi parte 1

**Comment by MauryCerda** [comment]
Excepciones Terminada.

En Java, las excepciones son eventos que ocurren durante la ejecución de un programa y que interrumpen el flujo normal de ejecución. Las excepciones se utilizan para manejar errores y situaciones excepcionales de manera controlada.
